Update Information

diff --git a/allssh b/allssh
--- a/allssh
+++ b/allssh
@@ -12,5 +12,15 @@
 ipnodes=( `sudo cat /etc/elasticsearch/discovery-file/unicast_hosts.txt | grep -e '^[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*$' | sort` )
 for ipnode in "${ipnodes[@]}"
 do
+  echo "================================================================================"
+  echo "START : ssh $ipnode $*"
+  echo "================================================================================"
+  echo
   ssh $ipnode $*
+  errorcmd=$?
+  echo
+  echo "================================================================================"
+  echo "RETURN : $errorcmd"
+  echo "================================================================================"
+  echo
 done
