Run local command in last

diff --git a/allssh b/allssh
--- a/allssh
+++ b/allssh
@@ -9,7 +9,8 @@
 
 ####### ALLSSH #######
 
-ipnodes=( `sudo cat /etc/elasticsearch/discovery-file/unicast_hosts.txt | grep -e '^[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*$' | sort` )
+iphost=`hostname -i`
+ipnodes=( `sudo cat /etc/elasticsearch/discovery-file/unicast_hosts.txt | grep -e '^[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*$' | grep -v $iphost | sort` )
 for ipnode in "${ipnodes[@]}"
 do
   echo "================================================================================"
@@ -24,3 +25,14 @@ do
   echo "================================================================================"
   echo
 done
+echo "================================================================================"
+echo "START : ssh $iphost $*"
+echo "================================================================================"
+echo
+ssh $iphost $*
+errorcmd=$?
+echo
+echo "================================================================================"
+echo "RETURN : $errorcmd"
+echo "================================================================================"
+echo
